# Generated by Django 4.1.7 on 2023-03-24 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_rename_name_user_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="token",
            new_name="password",
        ),
    ]
